### ISSUE TITLE
Submodules are private and require authenticating to github

### ISSUE THREAD

**Issue by romariorios** [terralang/terrac#3]
The filesystem and xopt submodules, required to build terrac, are private and require authentication when I try to update.

This prevents anyone without authorization to them from compiling terrac.

Not sure what to do here, since I'm not even able to know what these libraries are supposed to be, but they could be made public or there could be a copy of them inside terrac's repository.

**Comment by Qix-** [comment]
Sorry about that, I went ahead and updated the repo to use better cmake practices, remove the `filesystem` dependency since it's been standardized as part of c++17, and fixed the broken `xopt` dependency.

Thanks for letting me know :)

**Comment by romariorios** [comment]
Wohoo! Thanks for the quick response!
